import Head from "next/head"
import { useRouter } from "next/router"
import { useEffect } from "react"
import history from "../src/helpers/helper"

const Home = () => {
  const router = useRouter()

  useEffect(() => {
    if (router.pathname === "/") router.push("/login")
  })

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

export default Home
